Feature: Add sign up page & validation logic for sign up and login pages
CPG-Innovation-Team/cpx-web pull request #11
Opened 2022-09-09 01:41 UTC by fork1028

[JIRA 用户注册](https://cpg-innovate.atlassian.net/jira/software/c/projects/CPGI/boards/1?modal=detail&selectedIssue=CPGI-514)

* 添加用户注册页面
* 增加文本框校验逻辑

2022-09-09 08:24 UTC, casualbill requested changes

2022-09-09 08:24 UTC, casualbill commented on src/views/LoginPage.vue
> +};
这里我们之后可以考虑搞一个公共的校验方法

2022-09-09 08:24 UTC, casualbill commented on src/views/LoginPage.vue
> +};
暂时可以先放这边不用修改

2022-09-13 02:14 UTC, fork1028 commented on src/components/SignUp/CodeValidation.vue
> +  digit1: undefined,
https://github.com/ant-design/ant-design/issues/2367 <- 这个issue里面说了一些设计初衷，但是我刚刚试了一下null也是可以的，我把其他dropdown的undefined改成null了

2022-09-13 02:14 UTC, fork1028 commented on src/components/SignUp/CodeValidation.vue
> +    /^[0-9]{1}$/.test((formState.digit1 ? formState.digit1 : -1).toString()) &&
研究了一下还是把type改成string了。。感觉这样更合理点

2022-09-13 02:55 UTC, casualbill commented on src/components/SignUp/CodeValidation.vue
> +  digit1: undefined,
我个人的见解是，undefined可能更适合于变量类型未定义时的空值状况

2022-09-13 02:55 UTC, casualbill commented on src/components/SignUp/CodeValidation.vue
> +  digit1: undefined,
你之前的写法未必是错的，这个议题我们后续还可以继续深入研究^ ^

2022-09-13 03:00 UTC, casualbill approved these changes

2022-09-13 03:00 UTC, merged