Fix/styles: create separate components and clean code
CPG-Innovation-Team/cpx-web pull request #7
Opened 2022-09-01 03:26 UTC by fork1028

[UI页面组件化](https://cpg-innovate.atlassian.net/jira/software/c/projects/CPGI/boards/1?modal=detail&selectedIssue=CPGI-587)

* 重写`productDetail产品详情`页面
* 重写`supplierHomepage供应商主页`页面
* 增加了`buttonGroup`, `productPage`, `commentPage`, `moreProduct`, `previewModal`组件
* 修改了editProduct props数据传递
* 修改了variable命名
* 用flex替换a-row/a-col

2022-09-01 07:41 UTC, casualbill requested changes

2022-09-01 07:41 UTC, casualbill commented on src/components/ProductDetail/CommentPage.vue
> +          <template #icon><heart-outlined :style="{ color: 'grey' }" /></template>
这里又是两个小问题。。
1. color值建议用6位16进制数值表示
2. style的值是常量时采用非绑定写法

其实更建议用class的方式来写>_<

2022-09-01 07:41 UTC, casualbill commented on src/components/ProductDetail/CommentPage.vue
> +          <template #icon><heart-outlined :style="{ color: 'grey' }" /></template>
下面还有几处相同的。。。

2022-09-01 07:41 UTC, casualbill commented on src/components/ProductDetail/PreviewModal.vue
> +const emit = defineEmits(['set-flag']);
这里的Emit主要是用于组件间传参吗？
是有不方便通过Props传递参数的情况？

2022-09-01 07:41 UTC, casualbill commented on src/components/ProductDetail/PreviewModal.vue
> +  .ant-carousel :deep .slick-thumb li.slick-active img {
可能需要把后面的包进括号里，不然Vite编译会有warning
::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.

2022-09-01 07:41 UTC, casualbill commented on src/components/ProductDetail/PreviewModal.vue
> +  .ant-carousel :deep .slick-thumb li.slick-active img {
这里的样式可能可以通过Less nesting结合到上面的css里面去

2022-09-02 00:39 UTC, fork1028 commented on src/components/ProductDetail/CommentPage.vue
> +          <template #icon><heart-outlined :style="{ color: 'grey' }" /></template>
好的，漏改了😿

2022-09-02 03:08 UTC, casualbill commented on src/components/ProductDetail/PreviewModal.vue
> +const emit = defineEmits(['set-flag']);
这边不一定要改了，后续直接上Pinia

2022-09-06 02:56 UTC, casualbill approved these changes
有个Less样式的建议嵌套写法，仅供参考...
PR我先合了，样式后续看情况优化

2022-09-06 02:56 UTC, casualbill commented on src/components/ProductDetail/PreviewModal.vue
> +    }
可以看下如果这样写是否ok？
```

&:deep(.slick-thumb) {
  bottom: 0;

  li {
    width: 100px;
    height: 70px;

    img {
      display: block;
      width: 100px;
      margin-top: 10vh;
      padding: 5px 28px;
      background-color: #c9bdff;
      border-radius: 10%;
    }

    &.slick-active {
      img {
        border: 2px solid @primary-color;
        border-radius: 10%;
      }
    }
  }
}
```

2022-09-06 02:57 UTC, merged

2022-09-07 00:56 UTC, fork1028 commented on src/components/ProductDetail/PreviewModal.vue
> +    }
好的👌